# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.4.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files

  - repo: https://github.com/ambv/black
    rev: stable
    files: "./src/**/*"
    hooks:
      - id: black
    language_version: python3.7

  - repo: https://github.com/pre-commit/mirrors-isort
    rev: v4.3.21
    files: "./src/**/*"
    hooks:
      - id: isort
    additional_dependencies: [toml]
    language_version: python3.7
